### ISSUE TITLE
Using this config without changing to `legacyPackages`

### ISSUE THREAD

**Issue by oddlama** [lovesegfault/nix-config#1988]
Thanks for publishing your awesome config! When trying to adapt it to my own needs, I noticed that `nix flake check` always fails with the message

```
error: flake attribute 'packages.x86_64-linux.darwin' is not a derivation
```

The reason seems to be that the packages attribute set always requires to have derivations as the values, which somehow is not the case here. Renaming `packages` to `legacyPackages` fixes this, but this seems like a workaround to me. Judging by your activity you are using this config regularly, so I wonder what I am missing to make it work without using `legacyPackages`. I hope you can shed some light onto this.

**Comment by lovesegfault** [comment]
Should have been fixed by https://github.com/lovesegfault/nix-config/commit/d7ce72465ada2b94009bd4cb5336f92df278055d, can you confirm?

There was an issue with the weird recursive structure I was creating in `hosts.nix`, I ended up refactoring that whole thing to make it simpler.

`nix flake check` now passes.

**Comment by oddlama** [comment]
Thanks the issue is fixed now. Although the newly introduced structure seems to break when you don't define any hosts with `homeManager` as the type (as it will then not emit the `homeManager` attribute at all)

```
error: attribute 'homeManager' missing

       at /nix/store/xqfybkdsi4vsg3arr5v5jcgnl3m8210k-source/nix/home-manager.nix:9:11:

            8|   inherit (nixpkgs) lib;
            9|   hosts = (import ./hosts.nix).homeManager;
             |           ^
           10|
```

**Comment by lovesegfault** [comment]
Fixed by:
https://github.com/lovesegfault/nix-config/commit/0d528ae39c4f58f152dbe3e189040a6f03cd05b2
https://github.com/lovesegfault/nix-config/commit/c720068df07760980818acbb9cc8181e1aac779f
